name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    name: Deploy postgresql-sqlproxy to production environment on merge to main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create yaml file from secret
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'secret.yaml'
          encodedString: ${{ secrets.DATAFABRIKKEN_POSTGRESQL_PROD }}

      - name: Apply Helm template
        run: |
          helm template -f ${{ steps.write_file.outputs.filePath }} ./helm-sources/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Auth gcloud CLI for deploy
        uses: google-github-actions/auth@main
        with:
          credentials_json: ${{ secrets.DATAFABRIKKEN_PROD_AUTODEPLOY }}

      - name: Deploy to GCP & check status
        run: |
          gcloud container clusters get-credentials datafabrikken-prod --region europe-north1-a --project datafabrikken-prod
          kubectl apply -f ./kubectlapply.yaml --force
          if ! kubectl --namespace=prod rollout status deployment postgresql-sqlproxy; then
            kubectl --namespace=prod rollout undo deployment postgresql-sqlproxy
            kubectl --namespace=prod rollout status deployment postgresql-sqlproxy
            exit 1
          fi

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: postgresql-sqlproxy | Environment: prod'
          fields: commit,author,workflow,message
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
